#!/usr/bin/env python3
"""1. Async Comprehensions"""
from typing import List
async_generator = __import__("0-async_generator").async_generator


async def async_comprehension() -> List[float]:
    """Coroutine will collect 10 random numbers using an async comprehensing
    over async_generator, then return the 10 random numbers"""
    # Collect all numbers generated by async_generator into a list
    return [nmb_list async for nmb_list in async_generator()]
